#!/bin/sh

t=`basename $0`

cat > $t.I <<\EOF
#if(FOO)
EOF

cat > $t.EO <<\EOF
#if(FOO)
EOF

cat > $t.Ee <<\EOF
./cppi: standard input: unterminated #if, #ifdef, or #ifndef
EOF

expected_status=2

. ./test-common
