#!/bin/sh

t=`basename $0`

cat > $t.I <<\EOF
#if 0
#ifdef _AIX
#include "foo"
 #pragma alloca
#pragma alloca
#endif
#endif
EOF

cat > $t.EO <<\EOF
#if 0
# ifdef _AIX
#  include "foo"
  #pragma alloca
#  pragma alloca
# endif
#endif
EOF

cat > $t.Ee <<\EOF
EOF

options=
expected_status=0

. ./test-common
