#!/bin/sh

t=`basename $0`

# Don't create $t.I.
# This test makes sure that the command,
# `cppi -C dir non-existent-file' doesn't get an error.

cat > $t.EO <<\EOF
EOF

cat > $t.Ee <<\EOF
EOF

redirect_stdin=no
options='-C dir'
expected_status=0

. ./$srcdir/test-common
